# 노드가 담긴 alpine 이미지 가져오기
FROM node:10.15-alpine

# app 디렉토리 생성
RUN mkdir -p /app

#Docker 이미지 내부에서 RUN, CMD, ENTRYPOINT의 명령이 실행될 디렉터리를 설정합니다.
WORKDIR /app

# 현재 디렉터리에 있는 파일들을 이미지 내부 /app 디렉터리에 추가함
ADD     . /app

# // 소스 복사 
COPY . .

# //client 소스 실행
CMD ["npm","run","backend"]